
version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    restart: always


  frontend:
    build:
      context: ./Front-end
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./Front-end:/app
      - /app/node_modules
    depends_on:
      - backend


  backend:
    build:
      context: ./Back-end
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./Back-end:/app
      - /app/node_modules
      - ./Back-end/uploads:/app/uploads
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=JesaDB
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data: